apiVersion: orbixal.ai/v1
kind: agent

metadata:
  name: Orbixal Agent Hello World
  slug: orbixal_agent_hello_world
  version: 1.0.2
  description: Prints a message and exits successfully.
  tags:
    - example
    - hello-world
    - job

spec:
  build:
    context: "."
    dockerfile: Dockerfile

  runtime:
    type: container
    entrypoint:
      cmd:
        - /app/main.sh
    timeouts:
      startupSeconds: 30
      requestSeconds: 60
